### PR TITLE
Fixed importer freezing during long loads

### LINKED ISSUE #90: Importer currently feels like its freezing while loading large data sets
Need to change async implementation / show loading cursor etc. to improve user experience

### PR DESCRIPTION
**Pull request by MikeStower**
Resolves #90

### CODE REVIEW

File: Infrastructure/Infrastructure/Utilities/ExcelTools.cs [hunk 1]
```diff
@@ -14,26 +14,24 @@ public static DataSet ReadAsDataSet(string file)
         {
             var format = Path.GetExtension(file);
 
-            using (var stream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
-            {
-                IWorkbook book;
+            using var stream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
```
Comment (jbrider) [inline Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Are you sure this is right?
I thought the idea of the _using_ statement is that it cleans up after itself?

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Are you talking about the lack of closed braces following the _using_ statement? Because if so that's a new syntax option available (I think from C# 9) that the IDE kept pestering me to use. It functions exactly the same, just one less set of messy braces.

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Yep, that's what I was talking about.
So how does it know where the last bracket would be then?
Can you screen grab the hint from the IDE?

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Or find a reference somewhere that explains what it is doing and how it works now.

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Here's the prompt I'm seeing:

image

And the [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) for the feature (from C# 8 apparently).

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: I did a quick test, and it only makes that suggestion for _using_ blocks that encompass entire methods. When I added test code outside the block, the prompt disappeared. So if the method wasn't returning at the end of the _using_ block I would have to include the braces.

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: which probably means the using is superfluous as it has a return inside it

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: I don't think so, the way I've used the using statement is almost identical to the example I linked in the documentation. My understandstanding is that returning from the method won't necessarily release unmanaged resources like file streams because the GC doesn't know how to properly handle them. It's recommended to explicitly release such objects with _using_ or _Dispose()_ as soon as you're finished with them.

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Then I would move the return statement outside of the using block.
Are you checking if the file exists before it gets to this code?

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: The file is taken from an OpenFileDialog, so it has to exist to reach that point in the code. 
And that's the advantage of the new style of _using_. It works out from context when it's free to release the object, so you don't have to worry about what to include/exclude from the statement block.

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: No, it doesn't work out the context - the compiler replaces the using statement with the try...finally block at the end of it's scope now, not immediately after the end of the block statement as it did before.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement

Comment (MikeStower) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: Ahhh, my bad, I didn't realise using statements were compiled as try-finally blocks. But in that case moving the return location shouldn't make a difference right? Because a finally block executes as soon as you leave the try block, including when return is called, returning inside one is the same as calling return immediately afterwards - in both cases the finally block disposes the object and then the value is returned to the calling statement which continues execution. Or is there a distinction that I'm missing?

Comment (jbrider) [reply Infrastructure/Infrastructure/Utilities/ExcelTools.cs:17]: The new format will work in this case - just checking you understood why it works before merging it.
